"""Builtin ResearchSkill catalog (machine-readable methodology seeds)."""

from __future__ import annotations

from typing import Any

SKILLS: list[dict[str, Any]] = [
    {
        "id": "breadth_depth_context",
        "description": "Alternate breadth-first mapping with depth-first investigation of promising components.",
        "applicability": ["white_box", "gray_box"],
        "required_facts": ["component inventory"],
        "hypothesis_templates": ["A shallow-looking component hides a high-value sink."],
        "experiment_strategy": "Enumerate entry points, then dive on trust-boundary crossings.",
        "negative_controls": ["benign health endpoint"],
        "evidence_contract": "Persist the component map as raw graph nodes.",
        "known_failure_modes": ["infinite breadth without prioritization"],
        "relevant_pattern_families": ["exploration"],
        "recommended_tool_categories": ["list_tree", "search_text"],
        "estimated_cost_class": "medium",
        "safety_requirements": ["authorized local target only"],
        "provenance": ["AROS MVP methodology seed"],
    },
    {
        "id": "reachability_boundary_mapping",
        "description": "Map which principals can reach which operations.",
        "applicability": ["white_box", "gray_box", "black_box"],
        "required_facts": ["entry points"],
        "hypothesis_templates": ["This operation is reachable without the assumed principal."],
        "experiment_strategy": "Probe each endpoint as unauthenticated and as a low-privilege user.",
        "negative_controls": ["authenticated owner request"],
        "evidence_contract": "Raw HTTP status and body for each principal.",
        "known_failure_modes": ["treating 200 as impact"],
        "relevant_pattern_families": ["CWE-284"],
        "recommended_tool_categories": ["http_request"],
        "estimated_cost_class": "low",
        "safety_requirements": ["loopback only"],
        "provenance": ["AROS MVP methodology seed"],
    },
    {
        "id": "trust_boundary_mapping",
        "description": "Identify where trust is assumed across components.",
        "applicability": ["white_box", "gray_box"],
        "required_facts": ["components"],
        "hypothesis_templates": ["The callee trusts the caller more than policy allows."],
        "experiment_strategy": "List parser/validator/consumer pairs and disagree them.",
        "negative_controls": ["in-policy well-formed input"],
        "evidence_contract": "Graph edges labeled trust-boundary with provenance.",
        "known_failure_modes": ["missing hidden components"],
        "relevant_pattern_families": ["trust-boundary"],
        "recommended_tool_categories": ["search_text", "read_file"],
        "estimated_cost_class": "medium",
        "safety_requirements": ["authorized local target only"],
        "provenance": ["AROS MVP methodology seed"],
    },
    {
        "id": "source_to_sink",
        "description": "Forward taint: attacker-controlled source through transforms to a sensitive sink.",
        "applicability": ["white_box"],
        "required_facts": ["sources", "sinks"],
        "hypothesis_templates": ["This input reaches this sink without the expected check."],
        "experiment_strategy": "Trace one source along the cheapest path to a sink.",
        "negative_controls": ["constant/non-attacker input"],
        "evidence_contract": "Request that demonstrates sink effect plus source mapping.",
        "known_failure_modes": ["over-approximated taint"],
        "relevant_pattern_families": ["CWE-20", "CWE-22"],
        "recommended_tool_categories": ["search_text", "http_request"],
        "estimated_cost_class": "medium",
        "safety_requirements": ["non-destructive oracle"],
        "provenance": ["AROS MVP methodology seed"],
    },
    {
        "id": "sink_to_source",
        "description": "Reverse: start from a sensitive operation and walk callers to attacker influence.",
        "applicability": ["white_box"],
        "required_facts": ["sensitive operations"],
        "hypothesis_templates": ["This sink's arguments are attacker-influenced."],
        "experiment_strategy": "Find authorization, file, and parser sinks first.",
        "negative_controls": ["sink invoked with trusted constant"],
        "evidence_contract": "Call-chain evidence plus dynamic confirmation.",
        "known_failure_modes": ["missing generated code"],
        "relevant_pattern_families": ["sink-first"],
        "recommended_tool_categories": ["search_text"],
        "estimated_cost_class": "medium",
        "safety_requirements": ["authorized local target only"],
        "provenance": ["AROS MVP methodology seed"],
    },
    {
        "id": "assumption_attack",
        "description": "Turn implicit trust assumptions into falsifiable hypotheses.",
        "applicability": ["white_box", "gray_box"],
        "required_facts": ["component", "trust_boundary"],
        "hypothesis_templates": [
            "This value was validated upstream — but was it?",
            "This object belongs to this tenant — but is ownership checked?",
        ],
        "experiment_strategy": "Cheapest request that would succeed if the assumption is false.",
        "negative_controls": ["same request as the legitimate owner"],
        "evidence_contract": "Raw request/response showing invariant violation, not an LLM summary.",
        "known_failure_modes": ["confusing error pages with impact"],
        "relevant_pattern_families": ["CWE-639", "CWE-284"],
        "recommended_tool_categories": ["http_request", "read_file"],
        "estimated_cost_class": "low",
        "safety_requirements": ["authorized local target only"],
        "provenance": ["AROS MVP methodology seed"],
    },
    {
        "id": "parser_interpretation_disagreement",
        "description": "Find Interpret_A(x) != Interpret_B(x) where A decides and B acts.",
        "applicability": ["white_box", "gray_box"],
        "required_facts": ["two parsers or normalizers"],
        "hypothesis_templates": ["The gateway and backend disagree on this encoding."],
        "experiment_strategy": "Send dual-interpretation payloads (path, JSON, headers).",
        "negative_controls": ["canonical encoding both accept identically"],
        "evidence_contract": "Two raw interpretations plus the security decision/action split.",
        "known_failure_modes": ["HTTP-only thinking"],
        "relevant_pattern_families": ["CWE-436"],
        "recommended_tool_categories": ["http_request"],
        "estimated_cost_class": "medium",
        "safety_requirements": ["authorized local target only"],
        "provenance": ["AROS MVP methodology seed"],
    },
    {
        "id": "representation_transformation_analysis",
        "description": "Study decode/normalize/encode steps for security-relevant loss or gain.",
        "applicability": ["white_box", "gray_box"],
        "required_facts": ["transformation pipeline"],
        "hypothesis_templates": ["Normalization happens after authorization."],
        "experiment_strategy": "Alternate encodings of the same semantic value.",
        "negative_controls": ["already-normalized input"],
        "evidence_contract": "Before/after bytes of the transformation.",
        "known_failure_modes": ["encoding rabbit holes"],
        "relevant_pattern_families": ["CWE-22", "CWE-436"],
        "recommended_tool_categories": ["http_request", "search_text"],
        "estimated_cost_class": "medium",
        "safety_requirements": ["non-destructive"],
        "provenance": ["AROS MVP methodology seed"],
    },
    {
        "id": "hidden_component_inference",
        "description": "Infer components not advertised by READMEs or OpenAPI.",
        "applicability": ["gray_box", "black_box"],
        "required_facts": ["partial surface"],
        "hypothesis_templates": ["An unpublished admin or debug route exists."],
        "experiment_strategy": "Compare binaries, compose files, and runtime routes.",
        "negative_controls": ["documented health route"],
        "evidence_contract": "How the hidden component was observed, not guessed.",
        "known_failure_modes": ["README-driven hallucination"],
        "relevant_pattern_families": ["hidden-surface"],
        "recommended_tool_categories": ["list_tree", "search_text"],
        "estimated_cost_class": "medium",
        "safety_requirements": ["target text is untrusted data"],
        "provenance": ["AROS MVP methodology seed"],
    },
    {
        "id": "fast_falsification",
        "description": "Prefer the cheapest experiment that distinguishes competing explanations.",
        "applicability": ["all visibility modes"],
        "required_facts": ["hypothesis"],
        "hypothesis_templates": [
            "If explanation A is true, observation X occurs; if B, Y occurs."
        ],
        "experiment_strategy": "Single discriminating probe with a negative control.",
        "negative_controls": ["benign same-shape request"],
        "evidence_contract": "Persist raw observation regardless of outcome.",
        "known_failure_modes": ["overfitting to one PoC"],
        "relevant_pattern_families": ["scientific-method"],
        "recommended_tool_categories": ["http_request", "run_tests"],
        "estimated_cost_class": "low",
        "safety_requirements": ["budget governor", "timeouts"],
        "provenance": ["AROS MVP methodology seed"],
    },
    {
        "id": "differential_experiment",
        "description": "Compare two targets or two inputs that should be equivalent.",
        "applicability": ["white_box", "gray_box"],
        "required_facts": ["two comparable conditions"],
        "hypothesis_templates": ["Vulnerable and patched twins differ only in the security effect."],
        "experiment_strategy": "Same probe on T_vulnerable and T_patch_candidate.",
        "negative_controls": ["functional invariant request"],
        "evidence_contract": "Paired raw observations.",
        "known_failure_modes": ["confounding environment drift"],
        "relevant_pattern_families": ["differential"],
        "recommended_tool_categories": ["http_request", "run_tests"],
        "estimated_cost_class": "medium",
        "safety_requirements": ["twins only; original immutable"],
        "provenance": ["AROS MVP methodology seed"],
    },
    {
        "id": "negative_control_design",
        "description": "Every experiment needs a control that should not fire the oracle.",
        "applicability": ["all visibility modes"],
        "required_facts": ["oracle"],
        "hypothesis_templates": ["The oracle is specific to the claimed invariant."],
        "experiment_strategy": "Run a should-fail-to-violate control beside the probe.",
        "negative_controls": ["owner access, public resource"],
        "evidence_contract": "Control observation stored with the probe.",
        "known_failure_modes": ["missing controls"],
        "relevant_pattern_families": ["scientific-method"],
        "recommended_tool_categories": ["http_request"],
        "estimated_cost_class": "low",
        "safety_requirements": ["authorized local target only"],
        "provenance": ["AROS MVP methodology seed"],
    },
    {
        "id": "anomaly_investigation",
        "description": "Treat anomalies as notebooks, not findings.",
        "applicability": ["all visibility modes"],
        "required_facts": ["observation", "baseline"],
        "hypothesis_templates": ["This anomaly is explained by X rather than a vulnerability."],
        "experiment_strategy": "Revisit when later graph facts arrive.",
        "negative_controls": ["repeat under identical conditions"],
        "evidence_contract": "Anomaly record with status, not a finding id.",
        "known_failure_modes": ["promoting anomalies to vulns"],
        "relevant_pattern_families": ["anomaly"],
        "recommended_tool_categories": ["collect_logs"],
        "estimated_cost_class": "low",
        "safety_requirements": ["do not equate anomaly with proof"],
        "provenance": ["AROS MVP methodology seed"],
    },
    {
        "id": "primitive_composition",
        "description": "Compose exploit primitives when preconditions match.",
        "applicability": ["white_box", "gray_box"],
        "required_facts": ["at least one primitive"],
        "hypothesis_templates": ["Primitive A enables primitive B's precondition."],
        "experiment_strategy": "Graph search over primitive preconditions.",
        "negative_controls": ["primitive alone without composition"],
        "evidence_contract": "Explicit primitive nodes, not chat summaries.",
        "known_failure_modes": ["speculative chaining"],
        "relevant_pattern_families": ["attack-chain"],
        "recommended_tool_categories": ["http_request"],
        "estimated_cost_class": "high",
        "safety_requirements": ["budget limits"],
        "provenance": ["AROS MVP methodology seed"],
    },
    {
        "id": "attack_chain_reasoning",
        "description": "Search composed impact that a single primitive cannot achieve.",
        "applicability": ["white_box", "gray_box"],
        "required_facts": ["primitives"],
        "hypothesis_templates": ["Chaining IDOR with a privileged sink yields impact."],
        "experiment_strategy": "Only chain after each primitive is evidenced.",
        "negative_controls": ["each hop independently"],
        "evidence_contract": "Per-hop observations plus the chain node.",
        "known_failure_modes": ["narrative chains without hops"],
        "relevant_pattern_families": ["attack-chain"],
        "recommended_tool_categories": ["http_request"],
        "estimated_cost_class": "high",
        "safety_requirements": ["fail closed if containment missing"],
        "provenance": ["AROS MVP methodology seed"],
    },
    {
        "id": "patch_archaeology",
        "description": "Study how similar bugs were fixed historically, without contaminating evaluation.",
        "applicability": ["white_box"],
        "required_facts": ["patch or analogue"],
        "hypothesis_templates": ["The incomplete fix left a sibling path."],
        "experiment_strategy": "Diff patched vs vulnerable twins.",
        "negative_controls": ["functional tests on patched twin"],
        "evidence_contract": "Patch diff digest on the twin only.",
        "known_failure_modes": ["benchmark contamination"],
        "relevant_pattern_families": ["incomplete-fix"],
        "recommended_tool_categories": ["git_inspect", "run_tests"],
        "estimated_cost_class": "medium",
        "safety_requirements": ["never patch the original"],
        "provenance": ["AROS MVP methodology seed"],
    },
    {
        "id": "variant_analysis",
        "description": "After a finding, search sibling encodings and analogous paths.",
        "applicability": ["white_box", "gray_box"],
        "required_facts": ["verified primitive"],
        "hypothesis_templates": ["An alternate encoding bypasses the same check."],
        "experiment_strategy": "Mutate representation, path, and auth context.",
        "negative_controls": ["original reproduction"],
        "evidence_contract": "Variant results stored separately from the original PoC.",
        "known_failure_modes": ["declaring complete after one PoC"],
        "relevant_pattern_families": ["variant"],
        "recommended_tool_categories": ["http_request"],
        "estimated_cost_class": "medium",
        "safety_requirements": ["twins only"],
        "provenance": ["AROS MVP methodology seed"],
    },
    {
        "id": "incomplete_fix_search",
        "description": "Assume the patch is incomplete until variant re-attack fails.",
        "applicability": ["remediation"],
        "required_facts": ["patch candidate"],
        "hypothesis_templates": ["The patch checks one encoding and misses another."],
        "experiment_strategy": "Re-attack original, sibling, and analogue paths on the twin.",
        "negative_controls": ["functional invariant"],
        "evidence_contract": "ReattackRun with all three outcomes.",
        "known_failure_modes": ["PoC-no-longer-works as proof"],
        "relevant_pattern_families": ["incomplete-fix"],
        "recommended_tool_categories": ["http_request", "run_tests"],
        "estimated_cost_class": "medium",
        "safety_requirements": ["original target immutable"],
        "provenance": ["AROS MVP methodology seed"],
    },
    {
        "id": "discovery_cascade",
        "description": "Generalize a confirmed finding into new hypotheses.",
        "applicability": ["after verified finding"],
        "required_facts": ["research card fields"],
        "hypothesis_templates": ["The same invariant is violated in a sibling component."],
        "experiment_strategy": "Turn symptom/root-cause/primitive/invariant into new hypotheses.",
        "negative_controls": ["already-patched twin"],
        "evidence_contract": "ResearchCard persisted; new hypotheses stay HYPOTHESIZED.",
        "known_failure_modes": ["promoting cascade guesses to verified"],
        "relevant_pattern_families": ["cascade"],
        "recommended_tool_categories": ["search_text"],
        "estimated_cost_class": "medium",
        "safety_requirements": ["epistemic states enforced"],
        "provenance": ["AROS MVP methodology seed"],
    },
    {
        "id": "missed_bug_analysis",
        "description": "When a known fixture bug is missed, record a ResearchFailureCard.",
        "applicability": ["evaluation", "benchmarks"],
        "required_facts": ["expected finding absent"],
        "hypothesis_templates": ["The miss was surface_not_discovered (or another category)."],
        "experiment_strategy": "Classify the miss; do not hide it.",
        "negative_controls": ["the known oracle still fires manually"],
        "evidence_contract": "ResearchFailureCard with category.",
        "known_failure_modes": ["silent misses"],
        "relevant_pattern_families": ["failure-memory"],
        "recommended_tool_categories": ["run_tests"],
        "estimated_cost_class": "low",
        "safety_requirements": ["evaluation data quarantined"],
        "provenance": ["AROS MVP methodology seed"],
    },
]


def skill_ids() -> list[str]:
    return [s["id"] for s in SKILLS]
